spring:
  application:
    name: HelloService

server:
  port: 1080

eureka:
  instance:
    healthCheckUrlPath: /health
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    region: default
    eurekaServerPort: 8761
    useDnsForFetchingServiceUrls: true
    eurekaServerDNSName: eureka.intsit.sfdc.com.cn
    eurekaServerURLContext: eureka
    